/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.Alugados;
import dao.AlugadosDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.Util;

/**
 *
 * @author elvis
 */
public class frmAlugados extends javax.swing.JFrame {

    /**
     * Creates new form MenuClientes
     */
    public frmAlugados() {
        initComponents();

        loadItems("", "");
    }

    // Imports Globais
    private Util util = new Util();
    private Integer qtdToDo = 0;
    private ArrayList<Alugados> alugadosRequest = null;
    private Alugados gAlugados = new Alugados();

    /**
     * Metodo que carrega os ToDo
     *
     * @author Flavio Ever
     * @param placa placa do carro
     * @param cpf cpf do cliente
     * @since 10/05/2020
     */
    public void loadItems(String placa, String cpf) {
        qtdToDo = 0;

        String titulos[] = {"Placa", "Marca", "Modelo", "Preço Total", "Data Aluguel", "Data Retorno", "CPF", "Nome"};

        DefaultTableModel modelGrid = new DefaultTableModel(null, titulos) {
            @Override
            public boolean isCellEditable(int row, int column) {
                // Desabilita edição da jTable
                return false;
            }
        };

        alugadosRequest = (ArrayList<Alugados>) new AlugadosDAO().index(placa, cpf);

        for (int i = 0; i < alugadosRequest.size(); i++) {
            modelGrid.addRow(new Object[]{
                alugadosRequest.get(i).getPlaca(),
                alugadosRequest.get(i).getMarca(),
                alugadosRequest.get(i).getModelo(),
                "R$"+ alugadosRequest.get(i).getPrecoTotal(),
                alugadosRequest.get(i).getDataAluguel(),
                alugadosRequest.get(i).getDataRetorno(),
                alugadosRequest.get(i).getCpf(),
                alugadosRequest.get(i).getNome()
            });
            qtdToDo++;
        }

        lbQtd.setText(qtdToDo.toString());
        tbAlugados.setModel(modelGrid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtPlaca = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAlugados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnLiberarVeiculo = new javax.swing.JButton();
        lbQtd = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setText("Alugados");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 10, 190, 70);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(10000, 32767));
        jTabbedPane1.setOpaque(true);

        jPanel1.setLayout(null);

        txtPlaca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });
        txtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPlacaKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPlacaKeyReleased(evt);
            }
        });
        jPanel1.add(txtPlaca);
        txtPlaca.setBounds(210, 50, 100, 30);

        tbAlugados.setAutoCreateRowSorter(true);
        tbAlugados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Marca", "Modelo", "Preço Total", "Data Aluguel", "Data Retorno", "CPF", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbAlugados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbAlugadosMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAlugadosMouseClicked(evt);
            }
        });
        tbAlugados.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tbAlugadosCaretPositionChanged(evt);
            }
        });
        jScrollPane2.setViewportView(tbAlugados);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 110, 1140, 290);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("YOU -");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 50, 50, 30);

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCpfKeyReleased(evt);
            }
        });
        jPanel1.add(txtCpf);
        txtCpf.setBounds(160, 20, 150, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(20, 90, 1140, 12);

        btnLiberarVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/confirm_ico.png"))); // NOI18N
        btnLiberarVeiculo.setText("Liberar Veículo");
        btnLiberarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarVeiculoActionPerformed(evt);
            }
        });
        jPanel1.add(btnLiberarVeiculo);
        btnLiberarVeiculo.setBounds(500, 410, 200, 40);

        lbQtd.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lbQtd.setText("0");
        jPanel1.add(lbQtd);
        lbQtd.setBounds(460, 20, 100, 30);

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/search_ico.png"))); // NOI18N
        jLabel19.setText("Pesquisar Placa:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(20, 50, 140, 30);

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/search_ico.png"))); // NOI18N
        jLabel20.setText("Pesquisar CPF:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(20, 20, 140, 30);

        jLabel30.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel30.setText("Encontrados:");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(350, 20, 100, 30);

        jTabbedPane1.addTab("Status", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 90, 1190, 510);

        setSize(new java.awt.Dimension(1203, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbAlugadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAlugadosMouseClicked

    }//GEN-LAST:event_tbAlugadosMouseClicked

    private void tbAlugadosCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tbAlugadosCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tbAlugadosCaretPositionChanged

    private void btnLiberarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarVeiculoActionPerformed
        AlugadosDAO alugados = new AlugadosDAO();
        if (qtdToDo >= 1) {
            String rs = alugados.remove(gAlugados.getPlaca());

            if (!rs.equals("ok")) {
                JOptionPane.showMessageDialog(null, rs);
                return;
            }

            // Carrega items
            loadItems("", "");

            JOptionPane.showMessageDialog(null, "Veiculo liberado com sucesso!");
        }
    }//GEN-LAST:event_btnLiberarVeiculoActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void txtPlacaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyReleased
        txtCpf.setText(null);

        loadItems(txtPlaca.getText(), "");
    }//GEN-LAST:event_txtPlacaKeyReleased

    private void txtPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyTyped
        if (txtPlaca.getText().length() >= 4) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPlacaKeyTyped

    private void txtCpfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfKeyReleased
        txtPlaca.setText(null);

        if (util.cpfIsValid(txtCpf.getText())) {
            loadItems("", txtCpf.getText());
        }
    }//GEN-LAST:event_txtCpfKeyReleased

    private void tbAlugadosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAlugadosMouseReleased
         if (tbAlugados.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Nada selecionado");
        } else {
            int index = tbAlugados.getSelectionModel().getMinSelectionIndex();
            
            // Referencia pra Dropar
            gAlugados.setPlaca(alugadosRequest.get(index).getPlaca());
        }
    }//GEN-LAST:event_tbAlugadosMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAlugados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAlugados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAlugados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAlugados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAlugados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLiberarVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbQtd;
    private javax.swing.JTable tbAlugados;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
