/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import util.Util;
import classes.Cliente;
import classes.Veiculo;
import dao.ClienteDAO;
import dao.VeiculoDAO;
import java.awt.Toolkit;
import static java.time.Clock.system;
import javax.swing.JOptionPane;

/**
 *
 * @author elvis
 */
public class frmClientes extends javax.swing.JFrame {

    private frmVeiculos veioDoVeiculos;

    public frmClientes() {
        initComponents();
        abas.setEnabledAt(1, false);
        /*    if(rdInvisivel.isEnabled()==true){
        txtNome.setEnabled(false);
        txtSexo.setEnabled(false);
        txtCEP.setEnabled(false);
        txtRua.setEnabled(false);
        txtBairro.setEnabled(false);
        txtNumero.setEnabled(false);
        txtComplemento.setEnabled(false);
        txtCidade.setEnabled(false);
        txtEstado.setEnabled(false);
        txtEmail.setEnabled(false);
        txtCelular.setEnabled(false);
        }else{
            
        txtNome.setEnabled(true);
        txtSexo.setEnabled(true);
        txtCEP.setEnabled(true);
        txtRua.setEnabled(true);
        txtBairro.setEnabled(true);
        txtNumero.setEnabled(true);
        txtComplemento.setEnabled(true);
        txtCidade.setEnabled(true);
        txtEstado.setEnabled(true);
        txtEmail.setEnabled(true);
        txtCelular.setEnabled(true);    
        }
        
         */
    }

    public void setarVisivel() {
        if (rdVisivel.isEnabled()) {
            txtCPF.setEnabled(true);
            txtNome.setEnabled(true);
            txtSexo.setEnabled(true);
            txtCEP.setEnabled(true);
            txtRua.setEnabled(true);
            txtBairro.setEnabled(true);
            txtNumero.setEnabled(true);
            txtComplemento.setEnabled(true);
            txtCidade.setEnabled(true);
            txtEstado.setEnabled(true);
            txtEmail.setEnabled(true);
            txtCelular.setEnabled(true);
        }

    }

    public Cliente gravaCliente() {
        Cliente gravaCli = new Cliente();
        Util map = new Util();

        gravaCli.setCpf(map.parserCpf(txtCPF.getText()));
        gravaCli.setNome(txtNome.getText());
        gravaCli.setSexo(txtSexo.getText());
        gravaCli.setCep(txtCEP.getText());
        gravaCli.setRua(txtRua.getText());
        gravaCli.setBairro(txtBairro.getText());
        gravaCli.setNumero(txtNumero.getText());
        gravaCli.setComplemento(txtComplemento.getText());
        gravaCli.setCidade(txtCidade.getText());
        gravaCli.setEstado(txtEstado.getText());
        gravaCli.setEmail(txtEmail.getText());
        gravaCli.setCelular(map.parserCelular(txtCelular.getText()));

        System.out.println(gravaCli.getCpf() + " " + gravaCli.getCelular());
        return gravaCli;
    }

    public void buscaCliente() {

    }

    public void enviaAlugado(Veiculo vei) {
        txtPlaca.setText(vei.getPlaca());
        txtNomeCarro.setText(vei.getNome());
        txtMarca.setText(vei.getMarca());
        txtCategoria.setText(vei.getCategoria());
        txtClasse.setText(vei.getClasse());
        txtAno.setText(vei.getAno());
        txtPreco.setText(Float.toString(vei.getPreco()));
        txtCor.setText(vei.getCor());
        txtPortas.setText(vei.getPortas());
        abas.setEnabledAt(1, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        abas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSexo = new javax.swing.JTextField();
        txtCEP = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbCarros1 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btAlterar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        btCadastrar1 = new javax.swing.JButton();
        btConfirmar1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btConfirmarAlteracao = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        btPesqusar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        rdVisivel = new javax.swing.JRadioButton();
        rdInvisivel = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtComplemento = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtAno = new javax.swing.JLabel();
        txtCor = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtClasse = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JLabel();
        txtPortas = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtNomeCarro = new javax.swing.JLabel();
        btConfirmaAluguel = new javax.swing.JButton();
        btCancelarAluguel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setText("Clientes");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 20, 150, 50);

        abas.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        abas.setMaximumSize(new java.awt.Dimension(10000, 32767));
        abas.setOpaque(true);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentHidden(evt);
            }
        });
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("CPF:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 20, 50, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("CEP:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 140, 50, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Email:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(320, 180, 50, 30);

        txtSexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexoActionPerformed(evt);
            }
        });
        txtSexo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSexoKeyTyped(evt);
            }
        });
        jPanel1.add(txtSexo);
        txtSexo.setBounds(80, 60, 70, 30);

        txtCEP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCEPActionPerformed(evt);
            }
        });
        txtCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCEPKeyTyped(evt);
            }
        });
        jPanel1.add(txtCEP);
        txtCEP.setBounds(80, 140, 120, 30);

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });
        jPanel1.add(txtEmail);
        txtEmail.setBounds(370, 180, 320, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Bairro:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(20, 100, 50, 30);

        txtBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });
        txtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBairroKeyTyped(evt);
            }
        });
        jPanel1.add(txtBairro);
        txtBairro.setBounds(80, 100, 230, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nome:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(250, 20, 50, 30);

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });
        jPanel1.add(txtNome);
        txtNome.setBounds(310, 20, 380, 30);

        jPanel2.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("ID:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 20, 50, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("CEP:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 100, 50, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Telefone:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(20, 180, 70, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Email:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(20, 140, 50, 30);

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField8);
        jTextField8.setBounds(90, 180, 120, 30);

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField9);
        jTextField9.setBounds(90, 20, 90, 30);

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField10);
        jTextField10.setBounds(90, 100, 120, 30);

        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField11);
        jTextField11.setBounds(90, 140, 120, 30);

        tbCarros1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Classe", "Categoria", "Marca", "Cor", "Ano", "Placa", "Alugado", "Portas", "Preço"
            }
        ));
        jScrollPane3.setViewportView(tbCarros1);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(0, 350, 710, 140);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Endereço:");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(20, 60, 70, 30);

        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField12);
        jTextField12.setBounds(90, 60, 600, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Nome:");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(190, 20, 50, 30);

        jTextField13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField13);
        jTextField13.setBounds(240, 20, 450, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Telefone:");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(20, 220, 70, 30);

        jTextField14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField14);
        jTextField14.setBounds(90, 220, 120, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 0);

        txtEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });
        txtEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstadoKeyTyped(evt);
            }
        });
        jPanel1.add(txtEstado);
        txtEstado.setBounds(520, 140, 170, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Estado:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(460, 140, 50, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Celular:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(20, 180, 70, 30);

        txtCelular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });
        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelularKeyTyped(evt);
            }
        });
        jPanel1.add(txtCelular);
        txtCelular.setBounds(80, 180, 210, 30);

        txtCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });
        txtCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCidadeKeyTyped(evt);
            }
        });
        jPanel1.add(txtCidade);
        txtCidade.setBounds(280, 140, 170, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Cidade:");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(220, 140, 50, 30);

        jPanel4.setFocusCycleRoot(true);
        jPanel4.setFocusable(false);
        jPanel4.setLayout(null);

        btAlterar.setBackground(new java.awt.Color(204, 204, 204));
        btAlterar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        jPanel4.add(btAlterar);
        btAlterar.setBounds(330, 20, 150, 25);

        jPanel5.setFocusCycleRoot(true);
        jPanel5.setFocusable(false);
        jPanel5.setLayout(null);

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Alterar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8);
        jButton8.setBounds(170, 20, 150, 25);

        btCadastrar1.setBackground(new java.awt.Color(0, 0, 0));
        btCadastrar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCadastrar1.setText("Cadastrar");
        btCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrar1ActionPerformed(evt);
            }
        });
        jPanel5.add(btCadastrar1);
        btCadastrar1.setBounds(20, 20, 140, 25);

        btConfirmar1.setBackground(new java.awt.Color(0, 0, 0));
        btConfirmar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btConfirmar1.setText("Confirmar");
        btConfirmar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmar1ActionPerformed(evt);
            }
        });
        jPanel5.add(btConfirmar1);
        btConfirmar1.setBounds(330, 20, 150, 25);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Cancelar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6);
        jButton6.setBounds(490, 20, 150, 25);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(20, 240, 670, 60);

        btConfirmarAlteracao.setBackground(new java.awt.Color(204, 204, 204));
        btConfirmarAlteracao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btConfirmarAlteracao.setText("Confirmar");
        btConfirmarAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarAlteracaoActionPerformed(evt);
            }
        });
        jPanel4.add(btConfirmarAlteracao);
        btConfirmarAlteracao.setBounds(180, 20, 140, 25);

        btCadastrar.setBackground(new java.awt.Color(204, 204, 204));
        btCadastrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });
        jPanel4.add(btCadastrar);
        btCadastrar.setBounds(20, 60, 630, 25);

        btPesqusar.setBackground(new java.awt.Color(204, 204, 204));
        btPesqusar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPesqusar.setText("Pesquisar");
        btPesqusar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesqusarActionPerformed(evt);
            }
        });
        jPanel4.add(btPesqusar);
        btPesqusar.setBounds(20, 20, 140, 25);

        btCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        jPanel4.add(btCancelar);
        btCancelar.setBounds(500, 20, 150, 25);

        buttonGroup1.add(rdVisivel);
        rdVisivel.setSelected(true);
        rdVisivel.setText("visivel");
        rdVisivel.setFocusPainted(false);
        rdVisivel.setFocusable(false);
        rdVisivel.setNextFocusableComponent(jPanel4);
        rdVisivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdVisivelActionPerformed(evt);
            }
        });
        jPanel4.add(rdVisivel);
        rdVisivel.setBounds(580, 20, 30, 24);

        buttonGroup1.add(rdInvisivel);
        rdInvisivel.setText("Invisivel");
        rdInvisivel.setFocusPainted(false);
        rdInvisivel.setFocusable(false);
        rdInvisivel.setNextFocusableComponent(jPanel4);
        rdInvisivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdInvisivelActionPerformed(evt);
            }
        });
        rdInvisivel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rdInvisivelKeyReleased(evt);
            }
        });
        jPanel4.add(rdInvisivel);
        rdInvisivel.setBounds(560, 20, 40, 24);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(20, 230, 670, 100);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Rua:");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(170, 60, 50, 30);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Sexo:");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(20, 60, 40, 30);

        txtRua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuaActionPerformed(evt);
            }
        });
        txtRua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRuaKeyTyped(evt);
            }
        });
        jPanel1.add(txtRua);
        txtRua.setBounds(220, 60, 340, 30);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("Numero:");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(570, 60, 60, 30);

        txtNumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroKeyTyped(evt);
            }
        });
        jPanel1.add(txtNumero);
        txtNumero.setBounds(630, 60, 60, 30);

        txtComplemento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementoActionPerformed(evt);
            }
        });
        txtComplemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtComplementoKeyTyped(evt);
            }
        });
        jPanel1.add(txtComplemento);
        txtComplemento.setBounds(430, 100, 260, 30);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Complemento:");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(330, 100, 100, 30);

        txtPlaca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtPlaca);
        txtPlaca.setBounds(800, 380, 80, 30);

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });
        txtCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCPFKeyReleased(evt);
            }
        });
        jPanel1.add(txtCPF);
        txtCPF.setBounds(80, 20, 150, 30);

        abas.addTab("Cadastrar", jPanel1);

        jPanel3.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/InterDisciplinar/Logan.jpg"))); // NOI18N
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 20, 0, 0);

        txtPreco.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        txtPreco.setText("...");
        jPanel3.add(txtPreco);
        txtPreco.setBounds(610, 140, 80, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Valor:");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(540, 140, 50, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("YOU");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(590, 100, 40, 30);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("Placa:");
        jPanel3.add(jLabel30);
        jLabel30.setBounds(540, 100, 50, 30);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Ano:");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(360, 180, 50, 30);

        txtAno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAno.setText("...");
        jPanel3.add(txtAno);
        txtAno.setBounds(420, 180, 110, 30);

        txtCor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCor.setText("...");
        jPanel3.add(txtCor);
        txtCor.setBounds(420, 140, 110, 30);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Cor:");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(360, 140, 50, 30);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Classe:");
        jPanel3.add(jLabel27);
        jLabel27.setBounds(360, 100, 50, 30);

        txtClasse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtClasse.setText("...");
        jPanel3.add(txtClasse);
        txtClasse.setBounds(420, 100, 110, 30);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Marca:");
        jPanel3.add(jLabel34);
        jLabel34.setBounds(360, 60, 50, 30);

        txtMarca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMarca.setText("...");
        jPanel3.add(txtMarca);
        txtMarca.setBounds(420, 60, 110, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Categoria:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(540, 20, 70, 30);

        txtCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCategoria.setText("...");
        jPanel3.add(txtCategoria);
        txtCategoria.setBounds(610, 20, 80, 30);

        txtPortas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPortas.setText("...");
        jPanel3.add(txtPortas);
        txtPortas.setBounds(610, 60, 80, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Portas:");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(540, 60, 60, 30);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("Nome:");
        jPanel3.add(jLabel35);
        jLabel35.setBounds(360, 20, 50, 30);

        txtNomeCarro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNomeCarro.setText("...");
        jPanel3.add(txtNomeCarro);
        txtNomeCarro.setBounds(420, 20, 110, 30);

        btConfirmaAluguel.setBackground(new java.awt.Color(204, 204, 204));
        btConfirmaAluguel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btConfirmaAluguel.setText("Confirmar Aluguel");
        btConfirmaAluguel.setEnabled(false);
        btConfirmaAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmaAluguelActionPerformed(evt);
            }
        });
        jPanel3.add(btConfirmaAluguel);
        btConfirmaAluguel.setBounds(20, 280, 320, 60);

        btCancelarAluguel.setBackground(new java.awt.Color(204, 204, 204));
        btCancelarAluguel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCancelarAluguel.setText("Cancelar Aluguel");
        btCancelarAluguel.setEnabled(false);
        btCancelarAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarAluguelActionPerformed(evt);
            }
        });
        jPanel3.add(btCancelarAluguel);
        btCancelarAluguel.setBounds(370, 280, 320, 60);

        abas.addTab("tab2", jPanel3);

        getContentPane().add(abas);
        abas.setBounds(20, 80, 730, 400);

        setSize(new java.awt.Dimension(782, 544));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexoActionPerformed

    private void txtCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCEPActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "Deseja limpar os campos e reiniciar cadastro?");
        if (resp == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Consulte ou Cadastre um Cliente");

            txtCPF.setText("");
            txtNome.setText("");
            txtSexo.setText("");
            txtCEP.setText("");
            txtRua.setText("");
            txtBairro.setText("");
            txtNumero.setText("");
            txtComplemento.setText("");
            txtCidade.setText("");
            txtEstado.setText("");
            txtEmail.setText("");
            txtCelular.setText("");
            btCancelarAluguel.setEnabled(false);

            txtCPF.setEnabled(true);
            txtNome.setEnabled(true);
            txtSexo.setEnabled(true);
            txtCEP.setEnabled(true);
            txtRua.setEnabled(true);
            txtBairro.setEnabled(true);
            txtNumero.setEnabled(true);
            txtComplemento.setEnabled(true);
            txtCidade.setEnabled(true);
            txtEstado.setEnabled(true);
            txtEmail.setEnabled(true);
            txtCelular.setEnabled(true);

        } else if (resp == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Continue o cadastro");

        }

        /* 
        if(jButton5.isSelected()){
            rdInvisivel.setEnabled(false);
        }
        if(rdVisivel.isSelected()){
        txtNome.setEnabled(true);
        txtSexo.setEnabled(true);
        txtCEP.setEnabled(true);
        txtRua.setEnabled(true);
        txtBairro.setEnabled(true);
        txtNumero.setEnabled(true);
        txtComplemento.setEnabled(true);
        txtCidade.setEnabled(true);
        txtEstado.setEnabled(true);
        txtEmail.setEnabled(true);
        txtCelular.setEnabled(true);
            
        }
        if(rdInvisivel.isSelected()){
        txtNome.setEnabled(false);
        txtSexo.setEnabled(false);
        txtCEP.setEnabled(false);
        txtRua.setEnabled(false);
        txtBairro.setEnabled(false);
        txtNumero.setEnabled(false);
        txtComplemento.setEnabled(false);
        txtCidade.setEnabled(false);
        txtEstado.setEnabled(false);
        txtEmail.setEnabled(false);
        txtCelular.setEnabled(false);
        }
         */
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btCancelarAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarAluguelActionPerformed
        
    }//GEN-LAST:event_btCancelarAluguelActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        Util map = new Util();

        if (map.cpfIsValid(txtCPF.getText())) {
            //JOptionPane.showMessageDialog(null, "Digite um CPF valido!");
            JOptionPane.showMessageDialog(null, "CPF INVÁLIDO");
        } else {//coloca if nao tiver preenchido
        rdVisivel.setSelected(true);
        if (rdVisivel.isEnabled() == true) {
            txtNome.setEnabled(true);
            txtSexo.setEnabled(true);
            txtCEP.setEnabled(true);
            txtRua.setEnabled(true);
            txtBairro.setEnabled(true);
            txtNumero.setEnabled(true);
            txtComplemento.setEnabled(true);
            txtCidade.setEnabled(true);
            txtEstado.setEnabled(true);
            txtEmail.setEnabled(true);
            txtCelular.setEnabled(true);
            txtCPF.setEnabled(false);
            btCancelarAluguel.setEnabled(false);

        }
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        if (txtNome.isEnabled() == false) {
            JOptionPane.showMessageDialog(null, "Não pode alterar o cliente");
            int resp = JOptionPane.showConfirmDialog(null, "Deseja cadastrar um novo?");
            if (resp == JOptionPane.YES_OPTION) {
                txtCPF.setText("");
                txtNome.setText("");
                txtSexo.setText("");
                txtCEP.setText("");
                txtRua.setText("");
                txtBairro.setText("");
                txtNumero.setText("");
                txtComplemento.setText("");
                txtCidade.setText("");
                txtEstado.setText("");
                txtEmail.setText("");
                txtCelular.setText("");
                btCancelarAluguel.setEnabled(false);

                txtCPF.setEnabled(true);
                txtNome.setEnabled(true);
                txtSexo.setEnabled(true);
                txtCEP.setEnabled(true);
                txtRua.setEnabled(true);
                txtBairro.setEnabled(true);
                txtNumero.setEnabled(true);
                txtComplemento.setEnabled(true);
                txtCidade.setEnabled(true);
                txtEstado.setEnabled(true);
                txtEmail.setEnabled(true);
                txtCelular.setEnabled(true);

            }
        } else if (txtCPF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher CPF do cliente");

        } else if (txtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher NOME do cliente");
        } else if (txtSexo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher SEXO do cliente");
        } else if (txtCEP.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher CEP do cliente");
        } else if (txtRua.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher RUA do cliente");
        } else if (txtBairro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher BAIRRO do cliente");
        } else if (txtNumero.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher NUMERO do cliente");
        } else if (txtComplemento.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher COMPLEMENTO do cliente");
        } else if (txtCidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher CIDADE do cliente");
        } else if (txtEstado.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher ESTADO do cliente");
        } else if (txtEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher EMAIL do cliente");
        } else if (txtCelular.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher CELULAR do cliente");
        } else {

            Cliente cadastrar = gravaCliente();
            String resp = new ClienteDAO().gravarCliente(cadastrar);
            if (resp == "OK") {
                JOptionPane.showMessageDialog(null, "Cliente " + txtNome.getText() + " Cadastrado");
                System.out.println(resp);

                txtNome.setEnabled(false);
                txtSexo.setEnabled(false);
                txtCEP.setEnabled(false);
                txtRua.setEnabled(false);
                txtBairro.setEnabled(false);
                txtNumero.setEnabled(false);
                txtComplemento.setEnabled(false);
                txtCidade.setEnabled(false);
                txtEstado.setEnabled(false);
                txtEmail.setEnabled(false);
                txtCelular.setEnabled(false);
                btCancelarAluguel.setEnabled(true);

            }
        }
        /*if(txtNome){
            JOptionPane.showMessageDialog(null, "Não pode editar");
        }
        
        
        String resp = new ClienteDAO().gravarCliente(cadastrar);
        if (resp == "OK") {
            JOptionPane.showMessageDialog(null, "Cliente " + txtNome.getText() + " Cadastrado");
            System.out.println(resp);
        }

         */

    }//GEN-LAST:event_btCadastrarActionPerformed

    private void txtRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuaActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCadastrar1ActionPerformed

    private void btConfirmar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConfirmar1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btConfirmarAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarAlteracaoActionPerformed

        if (txtCPF.isEnabled() == false) {
            if (txtCPF.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Preencher CPF do cliente");

            } else if (txtNome.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Preencher NOME do cliente");
            } else if (txtSexo.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Preencher SEXO do cliente");
            } else if (txtCEP.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Preencher CEP do cliente");
            } else if (txtRua.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Preencher RUA do cliente");
            } else if (txtBairro.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Preencher BAIRRO do cliente");
            } else if (txtNumero.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Preencher NUMERO do cliente");
            } else if (txtComplemento.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Preencher COMPLEMENTO do cliente");
            } else if (txtCidade.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Preencher CIDADE do cliente");
            } else if (txtEstado.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Preencher ESTADO do cliente");
            } else if (txtEmail.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Preencher EMAIL do cliente");
            } else if (txtCelular.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Preencher CELULAR do cliente");
            } else {

                int resp = JOptionPane.showConfirmDialog(this, "Deseja confirmar a alteação?");
                if (resp == JOptionPane.YES_OPTION) {
                    String cli = new ClienteDAO().alteraClinte(gravaCliente());
                    txtNome.setEnabled(false);
                    txtSexo.setEnabled(false);
                    txtCEP.setEnabled(false);
                    txtRua.setEnabled(false);
                    txtBairro.setEnabled(false);
                    txtNumero.setEnabled(false);
                    txtComplemento.setEnabled(false);
                    txtCidade.setEnabled(false);
                    txtEstado.setEnabled(false);
                    txtEmail.setEnabled(false);
                    txtCelular.setEnabled(false);
                    txtCPF.setEnabled(true);
                    btCancelarAluguel.setEnabled(true);

                    if (cli == "OK") {
                        JOptionPane.showMessageDialog(null, "Cliente de CPF " + txtCPF.getText() + " Alterado!!!");
                    } else {
                        JOptionPane.showMessageDialog(null, cli);
                    }

                }
            }
        }


    }//GEN-LAST:event_btConfirmarAlteracaoActionPerformed

    private void jPanel1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentHidden

    }//GEN-LAST:event_jPanel1ComponentHidden

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void btConfirmaAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmaAluguelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConfirmaAluguelActionPerformed

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    private void btPesqusarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesqusarActionPerformed

        // Cliente cli = new ClienteDAO().buscaCliente(txtCPF.getText());
        /* if(txtCPF.isEnabled()==false){
            int resp = JOptionPane.showConfirmDialog(null, "Deseja pasar a alteração e Pesquisar?");

            if(resp == JOptionPane.YES_OPTION){

         */
 /*txtCPF.setText(cli.getCpf());
                txtNome.setText(cli.getNome());
                txtSexo.setText(cli.getSexo());
                txtCEP.setText(cli.getCep());
                txtRua.setText(cli.getRua());
                txtBairro.setText(cli.getBairro());
                txtNumero.setText(cli.getNumero());
                txtComplemento.setText(cli.getComplemento());
                txtCidade.setText(cli.getCidade());
                txtEstado.setText(cli.getEstado());
                txtEmail.setText(cli.getEmail());
                txtCelular.setText(cli.getCelular());
         */
    }//GEN-LAST:event_btPesqusarActionPerformed

    private void txtCPFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFKeyReleased
        Util map = new Util();

        if (map.cpfIsValid(txtCPF.getText())) {
            //JOptionPane.showMessageDialog(null, "Digite um CPF valido!");
            System.out.println("CPF INVÁLIDO");
        } else {

            Cliente cli = new ClienteDAO().buscaCliente(
                    map.parserCpf(txtCPF.getText())
            );

            if (cli != null) {
                txtCPF.setEnabled(true);
                txtCPF.setText(cli.getCpf());
                txtNome.setText(cli.getNome());
                txtSexo.setText(cli.getSexo());
                txtCEP.setText(cli.getCep());
                txtRua.setText(cli.getRua());
                txtBairro.setText(cli.getBairro());
                txtNumero.setText(cli.getNumero());
                txtComplemento.setText(cli.getComplemento());
                txtCidade.setText(cli.getCidade());
                txtEstado.setText(cli.getEstado());
                txtEmail.setText(cli.getEmail());
                txtCelular.setText(cli.getCelular());
                rdInvisivel.setSelected(true);
            }
        }

        if (rdVisivel.isEnabled() == true) {
            txtNome.setEnabled(true);
            txtSexo.setEnabled(true);
            txtCEP.setEnabled(true);
            txtRua.setEnabled(true);
            txtBairro.setEnabled(true);
            txtNumero.setEnabled(true);
            txtComplemento.setEnabled(true);
            txtCidade.setEnabled(true);
            txtEstado.setEnabled(true);
            txtEmail.setEnabled(true);
            txtCelular.setEnabled(true);

        }
        if (rdInvisivel.isSelected() == true) {
            txtNome.setEnabled(false);
            txtSexo.setEnabled(false);
            txtCEP.setEnabled(false);
            txtRua.setEnabled(false);
            txtBairro.setEnabled(false);
            txtNumero.setEnabled(false);
            txtComplemento.setEnabled(false);
            txtCidade.setEnabled(false);
            txtEstado.setEnabled(false);
            txtEmail.setEnabled(false);
            txtCelular.setEnabled(false);
            btCancelarAluguel.setEnabled(true);
        }
    }//GEN-LAST:event_txtCPFKeyReleased

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
        if(txtNome.getText().length() >=50){ 
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

        }

    }//GEN-LAST:event_txtNomeKeyTyped

    private void txtSexoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSexoKeyTyped
        if(txtSexo.getText().length() >=1){ 
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexoKeyTyped

    private void txtRuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRuaKeyTyped
    if(txtRua.getText().length() >=50){
	evt.consume();
        Toolkit.getDefaultToolkit().beep();
    
    }    
    }//GEN-LAST:event_txtRuaKeyTyped

    private void txtNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyTyped
        if(txtNumero.getText().length() >=7){ 
	evt.consume();
        Toolkit.getDefaultToolkit().beep();

    }
    }//GEN-LAST:event_txtNumeroKeyTyped

    private void txtComplementoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComplementoKeyTyped
        if(txtComplemento.getText().length() >=50){ 
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        
    }
    }//GEN-LAST:event_txtComplementoKeyTyped

    private void txtCidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCidadeKeyTyped
        if(txtCidade.getText().length() >=30){
	evt.consume();
        Toolkit.getDefaultToolkit().beep();

    }
    }//GEN-LAST:event_txtCidadeKeyTyped

    private void txtEstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoKeyTyped
        if(txtEstado.getText().length() >=30){
	evt.consume();
        Toolkit.getDefaultToolkit().beep();

    }
    }//GEN-LAST:event_txtEstadoKeyTyped

    private void txtCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyTyped
        if(txtCelular.getText().length() >=11){ 
	evt.consume();
        Toolkit.getDefaultToolkit().beep();

    }
    }//GEN-LAST:event_txtCelularKeyTyped

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
    if(txtEmail.getText().length() >=50){
            evt.consume();
        Toolkit.getDefaultToolkit().beep();


}
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtCEPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCEPKeyTyped
    if(txtCEP.getText().length() >=8){
            evt.consume();
        Toolkit.getDefaultToolkit().beep();
    }
    }//GEN-LAST:event_txtCEPKeyTyped

    private void txtBairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroKeyTyped
    if(txtBairro.getText().length() >=50){
	evt.consume();
        Toolkit.getDefaultToolkit().beep();
    
    }
    }//GEN-LAST:event_txtBairroKeyTyped

    private void rdVisivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdVisivelActionPerformed
        /*if(rdVisivel.isEnabled()==true){
            txtNome.setEnabled(true);
            txtSexo.setEnabled(true);
            txtCEP.setEnabled(true);
            txtRua.setEnabled(true);
            txtBairro.setEnabled(true);
            txtNumero.setEnabled(true);
            txtComplemento.setEnabled(true);
            txtCidade.setEnabled(true);
            txtEstado.setEnabled(true);
            txtEmail.setEnabled(true);
            txtCelular.setEnabled(true);

        }
        if(rdInvisivel.isSelected()==true){
            txtNome.setEnabled(false);
            txtSexo.setEnabled(false);
            txtCEP.setEnabled(false);
            txtRua.setEnabled(false);
            txtBairro.setEnabled(false);
            txtNumero.setEnabled(false);
            txtComplemento.setEnabled(false);
            txtCidade.setEnabled(false);
            txtEstado.setEnabled(false);
            txtEmail.setEnabled(false);
            txtCelular.setEnabled(false);
        }

        */
    }//GEN-LAST:event_rdVisivelActionPerformed

    private void rdInvisivelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rdInvisivelKeyReleased
        if (rdInvisivel.isEnabled() == true) {
            txtNome.setEnabled(false);
            txtSexo.setEnabled(false);
            txtCEP.setEnabled(false);
            txtRua.setEnabled(false);
            txtBairro.setEnabled(false);
            txtNumero.setEnabled(false);
            txtComplemento.setEnabled(false);
            txtCidade.setEnabled(false);
            txtEstado.setEnabled(false);
            txtEmail.setEnabled(false);
            txtCelular.setEnabled(false);
        }
    }//GEN-LAST:event_rdInvisivelKeyReleased

    private void rdInvisivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdInvisivelActionPerformed
        if (rdVisivel.isEnabled() == true) {
            txtNome.setEnabled(true);
            txtSexo.setEnabled(true);
            txtCEP.setEnabled(true);
            txtRua.setEnabled(true);
            txtBairro.setEnabled(true);
            txtNumero.setEnabled(true);
            txtComplemento.setEnabled(true);
            txtCidade.setEnabled(true);
            txtEstado.setEnabled(true);
            txtEmail.setEnabled(true);
            txtCelular.setEnabled(true);

        }
        if (rdInvisivel.isSelected() == true) {
            txtNome.setEnabled(false);
            txtSexo.setEnabled(false);
            txtCEP.setEnabled(false);
            txtRua.setEnabled(false);
            txtBairro.setEnabled(false);
            txtNumero.setEnabled(false);
            txtComplemento.setEnabled(false);
            txtCidade.setEnabled(false);
            txtEstado.setEnabled(false);
            txtEmail.setEnabled(false);
            txtCelular.setEnabled(false);
            btCancelarAluguel.setEnabled(true);
        }

    }//GEN-LAST:event_rdInvisivelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abas;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCadastrar1;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCancelarAluguel;
    private javax.swing.JButton btConfirmaAluguel;
    private javax.swing.JButton btConfirmar1;
    private javax.swing.JButton btConfirmarAlteracao;
    private javax.swing.JButton btPesqusar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JRadioButton rdInvisivel;
    private javax.swing.JRadioButton rdVisivel;
    private javax.swing.JTable tbCarros1;
    private javax.swing.JLabel txtAno;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JLabel txtCategoria;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JLabel txtClasse;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JLabel txtCor;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JLabel txtMarca;
    private javax.swing.JTextField txtNome;
    private javax.swing.JLabel txtNomeCarro;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JLabel txtPlaca;
    private javax.swing.JLabel txtPortas;
    private javax.swing.JLabel txtPreco;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtSexo;
    // End of variables declaration//GEN-END:variables
}
